export const SKILL_CATEGORIES: Record<string, string> = {
  'blog-cover-image-cli': 'Content & Blog',
  'cook-the-blog': 'Content & Blog',
  'noise2blog': 'Content & Blog',
  'schema-markup-generator': 'Content & Blog',
  'llms-txt-generator': 'Content & Blog',
  'human-tone': 'Content & Blog',
  'linkedin-post-generator': 'Social',
  'linkedin-job-post-to-buyer-pain-map': 'Social',
  'noise-to-linkedin-carousel': 'Social',
  'tweet-thread-from-blog': 'Social',
  'reddit-post-engine': 'Social',
  'reddit-icp-monitor': 'Social',
  'twitter-GTM-find-skill': 'Social',
  'show-hn-writer': 'Social',
  'competitor-pr-finder': 'PR & Press',
  'pr-description-writer': 'PR & Press',
  'producthunt-launch-kit': 'Launches',
  'oss-launch-kit': 'Launches',
  'product-update-logger': 'Launches',
  'hyperframes-product-launch-video': 'Launches',
  'vid-motion-graphics': 'Video & Graphics',
  'vid-product-launch': 'Video & Graphics',
  'vid-sizzle-reel': 'Video & Graphics',
  'graphic-case-study': 'Video & Graphics',
  'graphic-chart': 'Video & Graphics',
  'graphic-ebook': 'Video & Graphics',
  'graphic-gif': 'Video & Graphics',
  'graphic-slide-deck': 'Video & Graphics',
  'cold-email-verifier': 'Outreach & Sales',
  'email-newsletter': 'Outreach & Sales',
  'newsletter-digest': 'Outreach & Sales',
  'outreach-sequence-builder': 'Outreach & Sales',
  'meeting-brief-generator': 'Outreach & Sales',
  'map-your-market': 'Market Research',
  'where-your-customer-lives': 'Market Research',
  'pricing-finder': 'Market Research',
  'pricing-page-psychology-audit': 'Market Research',
  'position-me': 'Market Research',
  'gh-issue-to-demand-signal': 'Market Research',
  'hackernews-intel': 'Market Research',
  'google-trends-api-skills': 'Market Research',
  'meta-tribeV2-skill': 'Market Research',
  'meta-ads-skill': 'Ads & Growth',
  'brand-alchemy': 'Ads & Growth',
  'domain-expired-opportunity-finder': 'Ads & Growth',
  'vc-finder': 'Fundraising',
  'vc-curated-match': 'Fundraising',
  'yc-intent-radar-skill': 'Fundraising',
  'sdk-adoption-tracker': 'DevTools',
  'npm-downloads-to-leads': 'DevTools',
  'dependency-update-bot': 'DevTools',
  'docs-from-code': 'DevTools',
  'explain-this-pr': 'DevTools',
  'claude-md-generator': 'DevTools',
  'kill-the-standup': 'Internal Comms',
};

export const CATEGORY_ORDER = [
  'Content & Blog',
  'Social',
  'PR & Press',
  'Launches',
  'Video & Graphics',
  'Outreach & Sales',
  'Market Research',
  'Ads & Growth',
  'Fundraising',
  'DevTools',
  'Internal Comms',
  'Other',
];

export function categoryFor(skillName: string): string {
  return SKILL_CATEGORIES[skillName] || 'Other';
}
